apiVersion: v1
kind: Service
metadata:
  name: hackedvault-service
  labels:
    app: hackedvault
spec:
  selector:
    app: hackedvault
  ports:
    - name: web
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
