apiVersion: v1
kind: Service
metadata:
  name: bytevault-service
  labels:
    app: bytevault
spec:
  selector:
    app: bytevault
  ports:
    - name: web
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
